spring:
  application:
    name: telaria-backend
  datasource:
    url: jdbc:h2:file:./data/telaria-db
    driver-class-name: org.h2.Driver
    username: jorge
    password: prueba
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

keystore:
  location: keys.p12
  password: miclavedelkeystore
  private:
    name: jwt
    password: miclavedelkeystore

minio:
  endpoint: http://localhost:9000
  public-endpoint: http://10.164.206.49:9000
  access-key: admin
  secret-key: password123
  bucket: telaria-document-sharing
  presigned-url-expiration-minutes: 15
